---
title: "simulation"
author: "Kylie Wheelock Riley"
date: "10/31/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

set.seed(1)

knitr::opts_chunk$set(echo = TRUE)
```

Simulation using simple linear regressions
```{r}
sim_regression = function(n, beta0 = 2, beta1 = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}
```

```{r}
sim_regression(n = 30)
```

##rerun using a for loop
```{r}
output = vector("list", 100)

for (i in 1:100) {
  output[[i]] = sim_regression(30)
}

sim_results = bind_rows(output)
```

##rerun simulation using `purrr`
```{r}
sim_results = 
  rerun(100, sim_regression(30, 2, 3)) %>% 
  bind_rows()
```


```{r}
  sim_results %>% 
  ggplot(aes(x = beta0_hat, y = beta1_hat)) + 
  geom_point()
```



## Simulation: SLR for several ns
```{r}
n_list = list("n_30"  = 30, 
              "n_60"  = 60, 
              "n_120" = 120, 
              "n_240" = 240)
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = rerun(1000, sim_regression(n_list[[i]])) %>% 
    bind_rows
}

##Look at lecture after class for code
output[[1]] %>% 
  ggplot(aes(x = beta0_hat)
```

Taking code from above and trying to save it into 1 nicely formatted table
```{r}
simulate_n_regressions = function(n_runs = 100, n, beta0 = 2, beta1 = 3) {
  
  rerun(n_runs, sim_regression(n, beta0, beta1)) %>% 
    bind_rows()
  
}

sim_results = 
  tibble(
    sample_size = c(30, 60, 120, 240)
    ) %>% 
  mutate(
    estimate_dfs = map(.x = sample_size, ~simulate_n_regressions(n = .x))
    ) %>% 
  unnest
```

Post processing
```{r}
sim_results %>%
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size
  )
```

