---
title: "Writing Functions"
author: "Kylie Wheelock Riley"
date: "10/24/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)

set.seed(1)
```

We're going to write some functions. 

```{r}
x = rnorm(n = 30, mean = 4, sd = 2.3)
x_again = rnorm(n = 30, mean = 6, sd = .3)

(x - mean(x)) / sd(x)
(x_again - mean(x_again)) / sd(x_again)
```

Already getting complicated and getting a z score is one of the easiest things you can do.  Can write a function to simplify. 

```{r}
z_scores = function(x_arg) {
  ##adding conditional formatting so the function only works on the type of data you want
    if (!is.numeric(x_arg)) {
    stop("Argument x should be numeric")
  } else if (length(x_arg) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  z = (x_arg - mean(x_arg)) / sd(x_arg)
  z
  
}

z_scores(x)
```

try out the function
```{r, error = TRUE}
z_scores(x_arg = y)
##figure out what y is after class

z_scores(x = 3)
#does not work
z_scores("my name is jeff")
#does not work
z_scores(x = c(TRUE, TRUE, FALSE, TRUE))
#does work
z_scores(x = iris)
#does not work
```

## Multiple Outputs
```{r}
mean_and_sd = function(input_x) {
  
  if (!is.numeric(x_arg)) {
    stop("Argument x should be numeric")
  } else if (length(x_arg) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  tibble(
  mean_input = mean(input_x),
  sd_x = sd(input_x)
  )

  list(
    mean_input = mean(input_x), 
       sd_input = sd(input_x),
       z_score = (input_x - mean(input_x))/(sd(input_x))
  )
}
```

test the function above
```{r}

```

## Multiple Inputs
```{r}
  
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

##sim_data %>% 
 ## ggplot(aes(x = x, y = y)) +
 ## geop_point()

ls_fit = lm(y ~ x, data = sim_data)
  
beta0_hat = coef(ls_fit)[1]
##square bracket says give me the first coefficient (not a tidy way to do it)
beta1_hat = coef(ls_fit)[2]
##square bracket says give me the second coefficient

```

```{r}
sim_regression = function(n) {
  
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)


ls_fit = lm(y ~ x, data = sim_data)
  
beta0_hat = coef(ls_fit)[1]
##square bracket says give me the first coefficient (not a tidy way to do it)
beta1_hat = coef(ls_fit)[2]
##square bracket says give me the second coefficient
}

sim_regression( n = )
```

##Revisiting past examples
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = 
  read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()

reviews = 
  tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

Now create a function
```{r}
read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  review_titles = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  review_stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  review_text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}
```

